== Launching a billable stack
You will need the `python-heatclient` installed to use the `stack` subcommand.

To launch a stack execute:
-------
openstack stack create --template /path/to/the/tester/billable_stack.yaml --parameter flavor=<flavor> --parameter key=<your-key> --parameter public_network=<external-network> <your-stack-name>
-------
NOTE: Only `key` is a required parameter - the remaining ones have default values working on our platform.
Instead of writing passing the parameters from the command line, you can put them in a file and use the `--environment` flag.

This will create a Heat stack with all the billable resources.

== Pulling meters
Place the names of meters you want to check in the `required_meters.txt` - one in each line and run the main script passing the name or the ID of the stack you've created in the previous step:
-------
python show_billable_resources.py <your-stack-name>
-------
You will see a list of meters retrieved for all the billable resources in your stack and the timestamp of the latest meter. Compare this output with you list of meters to see whether there are any missing entries.

To get a more verbose output, add the `--verbose` flag:
-------
python show_billable_resources.py <your-stack-name> --verbose
-------
